# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50c10904c07021ebc4a392dc05ab87c8f3763ee17beabdd92c2a474ab3be5f581a9bcc23095715ec8cc266a20198e0ec4d9e067788b55f2678a94e171c8f4124

test:
  secret_key_base: 8649cda04ecf1d2a1f8b075cfa0c0a883842873cb565363f2f878f44e82677fddf27f2c44c3954b00148e5a1342297a14ca2ba2ed6bae7e93ed21abe8c72bbfe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
